# Generated by Django 3.2 on 2021-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifelogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='name',
            field=models.CharField(default='root', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
